spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?schema=category
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
server:
  port: 8081